### ISSUE TITLE
Create Child Info > ID Checklist Screen

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#13]
**STORY:** As a Kids ID App user, I want to enter information about my child's dentist, so I can share it with authorities should my child go missing.

**ASSUMPTIONS**
 User is logged in, and has created at least one child profile.
 User has navigated from the Child Info menu screen to "ID Checklist" option.

**ACCEPTANCE CRITERIA**
1. The ID Checklist screen will have the following list of checkbox fields:
     a. Child's Photo, preferably no more than 6 months old
     b. Child's Official Birth Certificate, preferably certified copy
     c. Child's Social Security Card 
     d. Child's Measurements (with link to Child Info > Measurements screen - See Issue #7)
     e. Child's Description (with link to Child Info > Physical Details screen - See Issue #8)
     f.  Child's Distinguishing Features (with link to Child Info > Distinguishing Features screen - See Issue #9 )
     g. Child's Friends (with link to Friends contacts functionality - See Issue #14)
     h. Child's DNA (with link to instruction screen on obtaining DNA - See Issue #15)
     i. Child's Mementos
     j. Certified copies of any divorce or custody papers
     k. Other parent(s) information (with link to Parent(s) and Family contacts functionality - See Issue #16)
2. All checkboxes are UNchecked by default.
3. When user checks a checkbox for a line item, it remains checked until a user unchecks the line item.
4. The ID Checklist screen will have a link/button for "Documents" which will send the user to the Documents functionality ( #30 )

**REFERENCES**
[MCM.pdf](https://github.com/HTBox/MobileKidsIdApp/files/120988/MCM.p)

**Comment by CoderNate** [comment]
Per Alex, for now the checklist is just meant to be a dumb list that the user checks and un-checks items in.  It isn't actually aware of which types of documents you've loaded.  Maybe later we'll change it so that some items are a read-only check box that tells you if you've loaded a certain document or not.
