### ISSUE TITLE
Provide documentation for how to run the app

### ISSUE THREAD

**Issue by bignis** [HTBox/MobileKidsIdApp#132]
I was tipped off to the existence of this project by @rockfordlhotka and thought I'd check it out.  I'm interested in finding out how I can run the application (so I can see what it looks like) and possibly find a place to make a contribution.

From the docs folder I see stuff about Azure deployment, local dev environment setup, testing, etc but nothing currently that would tell me how to run the app.

Maybe it's simply a link to an App Store download?  Maybe it's instructions on deploying it to a locally-attached device?  Maybe emulator instructions?  Not sure what's most practical.

(feel free to move / close if this isn't the right venue for this suggestion/question)

**Comment by rockfordlhotka** [comment]
Ultimately the app will be available in the various platform stores. Right now the only way to run it is by setting up a dev environment and running it on your dev device or in an emulator.

We have taken some steps toward getting it to deploy via HockeyApp, but that is not fully functional at this point.
