### ISSUE TITLE
Set up src for Xamarin spike

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#133]
We are going to give Xamarin.Forms a try, and this issue involves removing all the contents of the src folder and replacing it with a Xamarin solution.

**Comment by bseebacher** [comment]
Wow. So far, so good, eh?

**Comment by rockfordlhotka** [comment]
Yes, making good progress!

**Comment by bseebacher** [comment]
Hey @rockfordlhotka : Have you pushed up the CSLA-XamarinForms update to NuGet yet? I just did a merge of your stuff from last night, and it's falling over trying to restore 4.6.400-Beta-16050904.

**Comment by rockfordlhotka** [comment]
Pushing now, sorry @bseebacher !

**Comment by bseebacher** [comment]
No problem, @rockfordlhotka. Just did a rebuild, and voila...
