### ISSUE TITLE
Instruction Screen - Child's DNA

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#15]
**STORY:** As a Kids ID App user, I want to find information on obtaining my child's DNA, in case I need to share this information should my child go missing.

**ASSUMPTIONS**
User is logged in, and has created at least one child profile.
User has navigated to the Child's DNA instruction screen (e.g. from the ID Checklist screen #13 ).

**ACCEPTANCE CRITERIA**
The Child's DNA instruction screen will contain the text included in the referenced attachment.

**REFERENCES**
[How to do a Home DNA Collection for your child.docx](https://github.com/HTBox/MobileKidsIdApp/files/131497/How.to.do.a.Home.DNA.Collection.for.your.child.docx)

**Comment by usernamesarepasse** [comment]
#74
