### ISSUE TITLE
Contacts Functionality - Other Parent(s) and Family

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#16]
**STORY:** As a Kids ID App user, I want to identify my child's other parent(s) and family and access their contact information, in case I need to share this information should my child go missing.

**ASSUMPTIONS**
 User is logged in, and has created at least one child profile.
 User has navigated to the Other Parent(s) and Family contacts screen (e.g. from the ID Checklist screen #13 ).
 User has at least one contact for their child's other parents and/or family in their mobile contacts list.

**ACCEPTANCE CRITERIA**
1. The Other Parent(s) and Family screen displays help text and the ability to add up to 10 entries the Child's parent(s) or family.
2. The help text will read: "Choose up to 10 contacts for your child's other parent(s) or family. Including the following information about other parent(s) and their family is recommended: names, addresses, phone numbers, Social Security number, vehicle license plate number(s), employment information, and credit & banking information, if known."
3. When the user chooses to create an entry for another parent or family member, the user can select from existing mobile contacts in their contact list.
4. The user can select up to 10 mobile contacts as other parent(s) or family.
5. Once 10 contacts are selected, the user is prohibited from adding more contacts until they unlink at least one of their parent or family entries.
6. Unlinking a parent or family entry in Kids ID App will not delete the contact from the user's mobile contacts, just remove the link between the contact and the app.

**Comment by jacob-maristany** [comment]
Closing this issue as it stands. After discussing with @rockfordlhotka , we are removing the ability to select contacts from the device and replacing with manual entry based on the following: 

a) the limited information contact picking provides and what is used
b) the potential for irrelevant and informal information (e.g. "Grandpa Jacob", "Joe", "My son's friend") and how limited the functionality is based on the contacts on the user's specific device
c) how unintuitive the value or functionality of the feature is to the user
d) as an app that cares significantly about PII, restricting app permissions that aren't really needed for critical features
