### ISSUE TITLE
Physical Details Screen (Xamarin)

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#164]
Related to #8

**Comment by bseebacher** [comment]
I'm working on this right now. Everything works except for binding the MeasurementDate to the DatePicker, which is throwing an exception for some reason. It looks the same as the one on the BasicDetails.

I'll keep digging, but maybe @rockfordlhotka knows a secret handshake that I don't.

**Comment by bseebacher** [comment]
Turns out the stock date picker doesn't handle nullable dates. The reason I hadn't seen this in the BasicDetails view is that we haven't hooked in any UI for a new child yet. (Amaria and Mario both have nice non-null birthdays.)

Since we're likely to hit this bump again, we may want to consider subclassing the date picker and doing something like what these guys did.

https://forums.xamarin.com/discussion/20028/datepicker-possible-to-bind-to-nullable-date-value

Thoughts?

**Comment by rockfordlhotka** [comment]
Either that, or we can examine the various DateTime fields in the user scenarios and decide whether they should actually be nullable.

**Comment by bseebacher** [comment]
In this case (measurement date), I think a null is appropriate. You might have a ballpark idea of the height and weight of your kid, but you may not recall when a formal measurement was performed.

If we wanted to sidestep null here, I suppose we could use today's date as the default. The user isn't likely to change these things much. Just recording the date on which it was modified may be as good as anything.

**Comment by rockfordlhotka** [comment]
I would think even an approximate date is better than no date at all, at least in this case.

**Comment by tlhotkamcm** [comment]
Agreed, if the user does not supply a date, the application can default to "today's date" and most times be "close enough"

-----Original Message-----

**Comment by bseebacher** [comment]
Works for me. I'll make it so.

@rockfordlhotka : Any opinions on where/how we should set defaults in the child objects? I roughed this one in for now in the mock storage constructor, but I assume there's a CSLA pattern to follow.

**Comment by rockfordlhotka** [comment]
Yes @bseebacher - default values for new objects should be set in the DataPortal_Create method within the business class. You can override the base class method and just set the property values there.

**Comment by bseebacher** [comment]
I'm punting on the Create methods for now, since we haven't implemented a "new child" hook yet. Will revisit later.
