### ISSUE TITLE
ICloneable not present in mono on Android?

### ISSUE THREAD

**Issue by CoderNate** [HTBox/MobileKidsIdApp#168]
I get the following error when I click the save button in the child profile list screen when running in an Android emulator:
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.ICloneable' from assembly 'Csla, Version=4.6.400.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30'.
05-15 08:44:46.216 E/mono-rt ( 2115):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine] (System.Runtime.CompilerServices.TStateMachine& stateMachine) [0x00039] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:833 
05-15 08:44:46.216 E/mono-rt ( 2115):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (System.Runtime.CompilerServices.TStateMachine& stateMachine) [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:447 
05-15 08:44:46.216 E/mono-rt ( 2115):   at Csla.Xaml.ViewModelBase`1[T].SaveAsync () [0x00023] in <filename unknown>:0 
05-15 08:44:46.216 E/mono-rt ( 2115):   at MobileKidsIdApp.ViewModels.ChildProfileList+<<-ctor>b__8_0>d.MoveNext () [0x0000e] in C:\Users\Admin\Documents\Programs\MobileKidsIdApp\src\MobileKidsIdApp\MobileKidsIdApp\MobileKidsIdApp\ViewModels\ChildProfileList.cs:20 
05-15 08:44:46.216 E/mono-rt ( 2115): --- End of stack trace from previous location where exception was thrown ---

**Comment by rockfordlhotka** [comment]
I am narrowing down the issue that's causing this - has something to do with type redirection in the CSLA PCL - hopefully have a fix soon.

**Comment by rockfordlhotka** [comment]
For tracking purposes, here is the relevant CSLA issue: https://github.com/MarimerLLC/csla/issues/575
