### ISSUE TITLE
Create About MCM Screen

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#19]
**STORY:**  As a Kids ID App user, I want to read information about Missing Children Minnesota, so I can learn about the organization.

**ASSUMPTIONS**
User is logged into the app.
User has navigated to the About MCM screen.

**ACCEPTANCE CRITERIA**
1. The screen will contain the copy text in the attached About MCM copy document, including section headers: Our Story, Our Mission, Our History, Our Affiliations and Contact Us.
2. The screen will display the logos included in the attached document, adjacent to the sections as shown the document:
a. MCM logo adjacent the first paragraph of Our Story
b. AMECO logo adjacent the bullet list text copy for AMECO, under Our Affiliations
c. Community Shares logo adjacent the text copy for Community Shares, under Our Affiliations

**REFERENCES**
1. [About MCM copy.docx](https://github.com/HTBox/MobileKidsIdApp/files/133254/About.MCM.copy.docx)
2. AMECO Logo ![ameco logo](https://cloud.githubusercontent.com/assets/16962381/13090317/96ba83f0-d4ba-11e5-944e-28801c37b47d.jpg)
3. Community Shares Logo ![community shares logo](https://cloud.githubusercontent.com/assets/16962381/13090318/96bb4d08-d4ba-11e5-8b4b-463562b6cdbf.png)
4. MCM Logo ![mcm logo](https://cloud.githubusercontent.com/assets/16962381/13090319/96bca8a6-d4ba-11e5-9210-00492e515f32.jpg)

**Comment by bseebacher** [comment]
Side Notes:

While working through implementing this, I noticed the web link provided in the document wasn't accurate. I was able to find the site via search (http://missingchildrenmn.com).

I also noticed that the SSL certificate isn't signed to the domain; probably something that should be fixed.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/7266719/41819738-4d66db24-778b-11e8-973d-fd70aee22f14.png">

Will someone be able to update the logo on the site to match what the app will have?
