### ISSUE TITLE
Eliminate Save button: autosave changes when user leaves each page

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#198]
Right now the user must click Save on the main family view (list of children), which is not a good experience. Mobile users expect things to auto-save as they leave each screen, so we need to make the app do that type of behavior.

**Comment by rockfordlhotka** [comment]
Current train of thought is to enhance CSLA to support in-place editing of the object graph. If CSLA supported that concept, then we could save the top-level family root object without needed to rebind any existing view/viewmodel bindings that connect to the model graph.

As a result this is now on Rocky's shoulders to look at this enhancement for CSLA.

**Comment by bseebacher** [comment]
We successfully hooked the OnDisappearing event of ContentPage as the point at which to save changes on the active screen without requiring a save button click.

**Comment by rockfordlhotka** [comment]
Using the latest enhancement to CSLA (`GraphMerger`) I was able to use the `OnDisappearing` event of all child detail pages to auto-save data as the user leaves each page.
