### ISSUE TITLE
Instruction Screen - Child Safety Info

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#20]
**STORY:** As a Kids ID App user, I want to find information on child safety, so I can be informed and teach my child(ren) about being safer.

**ASSUMPTIONS**
User is logged in, and has navigated to the Child Safety instruction screen.

**ACCEPTANCE CRITERIA**
The Child Safety instruction screen will contain the text included in the referenced attachment, including section headers.

**REFERENCES**
[Child Safety copy.docx](https://github.com/HTBox/MobileKidsIdApp/files/133307/Child.Safety.copy.docx)

**Comment by usernamesarepasse** [comment]
#74
