### ISSUE TITLE
Can't add details to lists of child info

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#202]
Things like adding a distinguishing feature or friend or family member all fail when trying to add a new object to the collection: error is that the object needs to be marked as a child object.

**Comment by bseebacher** [comment]
Decided at this point to defer friend list feature until next release. We will ship this version with a "coming soon" screen.

**Comment by rockfordlhotka** [comment]
Superseded by other bug reports.
