### ISSUE TITLE
Instruction Screen - If Your Child Is Missing

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#21]
**STORY:** As a Kids ID App user, I want to find information what to do if my child is missing, so I can be informed and take the necessary steps.

**ASSUMPTIONS**
User is logged in, and has navigated to the If Your Child Is Missing instruction screen.

**ACCEPTANCE CRITERIA**
The If Your Child Is Missing instruction screen will contain the text included in the referenced attachment, including section headers.

**REFERENCES**
[If Your Child is Missing copy.docx](https://github.com/HTBox/MobileKidsIdApp/files/133330/If.Your.Child.is.Missing.copy.docx)

**Comment by usernamesarepasse** [comment]
#74
