### ISSUE TITLE
Instruction Screen - If Your Child Runs Away

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#22]
**STORY:** As a Kids ID App user, I want to find information what to do if my child runs away, so I can be informed and take the necessary steps.

**ASSUMPTIONS**
User is logged in, and has navigated to the If Your Child Runs Away instruction screen.

**ACCEPTANCE CRITERIA**
 The If Your Child Runs Away instruction screen will contain the text included in the referenced attachment, including section headers.

**REFERENCES**
[If Your Child Runs Away copy.docx](https://github.com/HTBox/MobileKidsIdApp/files/133336/If.Your.Child.Runs.Away.copy.docx)

**Comment by usernamesarepasse** [comment]
#74
