### ISSUE TITLE
Logo/icon design proposal

### ISSUE THREAD

**Issue by teneresa** [HTBox/MobileKidsIdApp#220]
Dear Sirs, 
hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design. If it's something you're interested in, please, let me know!
Best,
Valeria

**Comment by rockfordlhotka** [comment]
That is wonderful Valeria, we're thrilled to have you involved as a collaborator!

MCM does have an official logo for their organization, but we do not have icons at this time.

**Comment by teneresa** [comment]
Hi Rockford, and thank you for your reply! 
I'm glad to participate in such an important project! Could you please clarify some information that I could take into account to develop the most suitable design.
1. Where do you plan to use the icon? Google Play, Apple Store? Somewhere else?
2. Should it include any text or any specific object?
3. Colorful or black & white?
Any other wishes?
Best,
Valeria

**Comment by rockfordlhotka** [comment]
We plan to release the app on iOS, Android, and Windows 10 (Microsoft Store). So we'll need icons for all three stores, in all the resolutions supported by those stores and their devices. I think the resolutions are different for each store?

There are some graphic resources (the MCM logo, and a style guide) in this repo:
https://github.com/HTBox/MobileKidsIdApp/tree/master/resources

I think the icons should have color, based on the style sheet, and probably the teal used in the colorful version of the logo.

**Comment by teneresa** [comment]
Rockford, hi and thanks for the information! I'm starting to work on the icons.

**Comment by teneresa** [comment]
Rockford, hi, I made some options of the icon for your App. Please have a look. I'm waiting for your feedback.
![kidsidapp-01](https://user-images.githubusercontent.com/39339824/41118824-7dd17264-6a67-11e8-9c6d-3e09cd9e3136.jpg)

**Comment by teneresa** [comment]
Rockford, I prepared all the files, [here](https://drive.google.com/open?id=1nd3PeB6Bqhd1SmyDos5MwK-5-ltK6H_o) is a link to my Google drive. Please, check it!
I made PNG files for Apple store, Google Play and Windows 10. There are also SVG files that you can use for web, etc. and vector files with all other sizes, that you can also use to make any PNG, JPG, etc. if it's required. 
![screen 01](https://user-images.githubusercontent.com/39339824/41569339-19ac9b8c-7341-11e8-834e-841e78039c1a.png)

Please, let me know if everything is Ok.

**Comment by teneresa** [comment]
Rockford, hi, how are you? I'd like to create a pull-request if everything is ok with the files. Can I do this?

**Comment by rockfordlhotka** [comment]
Yes please! Probably put the content in the top-level resources folder?

**Comment by teneresa** [comment]
I uploaded the content to the resources folder and updated Readme file. Please check it and merge if everything is ok.
