### ISSUE TITLE
Update ContactPicker functionality

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#226]
After upgrading to netstandard 2.0, the contact picker plugin we were using is no longer available. We need to replace that functionality (marked with TODO comments) with an updated implementation.

**Comment by brunck** [comment]
I'll start looking at this

**Comment by brunck** [comment]
This already works on iOS, and apparently already works on UWP as well although I'm not able to personally confirm the latter.

**Comment by rockfordlhotka** [comment]
I'm going to close the issue then. If there are issues they'll get logged as bugs.
