### ISSUE TITLE
Instruction Screen - About Parental Abduction

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#23]
**STORY:** As a Kids ID App user, I want to find information about parental abduction, so I can be informed and take the necessary prevention steps.

**ASSUMPTIONS**
User is logged in, and has navigated to the About Parental Abduction instruction screen.

**ACCEPTANCE CRITERIA**
The About Parental Abduction instruction screen will contain the text included in the referenced attachment, including section headers.

**REFERENCES**
[About Parental Abduction copy.docx](https://github.com/HTBox/MobileKidsIdApp/files/133347/About.Parental.Abduction.copy.docx)

**Comment by usernamesarepasse** [comment]
#74
