### ISSUE TITLE
Display Terms of Use / Policy Statements

### ISSUE THREAD

**Issue by bseebacher** [HTBox/MobileKidsIdApp#235]
As an officer of Missing Children Minnesota, I need to display our terms of use, copyrights, and other applicable policy statements within the app so that users can be made aware of the legal implications of using it.

**Notes**

* We may choose not to list this app in EU locales due to GDPR requirements. Even though we are not storing any data on a server, there may be some other things about this app that could trip us up, particularly storing data about children.
* Is there already MCM boilerplate legal language available?

**Comment by rockfordlhotka** [comment]
Probably related to #62 - I'd think these things might be combined into a single dialog?

**Comment by rockfordlhotka** [comment]
I am going to close this, as I think it is covered by #62
