### ISSUE TITLE
Set up dev/staging Azure instance for the Feb 2016 codeathon

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#24]

**Comment by BillWagner** [comment]
Tagging @tonysurma 

There are a few items we need to address here:

*[ ] Do we setup a site on the HTBox account before the codeathon, have one of the codeathon folks host for the weekend (the latter would make it easier for attendees to set config settings during the event)
*[ ] How do we setup a staging site, and protect, or ensure that user data is fake? (We do not want parents mistakenly entering information in the staging site)
*[ ] How do we coordinate the staging / live site with the mobile apps (for development vs. production device usage)?

There may be more, but this is my initial list of concerns / thoughts.

**Comment by jwendl** [comment]
Could use ARM templates to help facilitate azure resources in different resource groups. One resource group for "Production" another resource group for "Staging". Then have the "app settings" in the ARM templates point to the right hosts so things don't get mixed up. 

On the staging site, could read the config or app setting and have a notification banner on the top saying "staging site only" for each page or something like that.

**Comment by tonysurma** [comment]
ARM templates or something else would be good - we have seen our environments are pretty simple (web app + db) and only 2 environments so been doing them by hand. I would propose for this weekend someone local with a sub set things up (happy to consult on what we have done) and then we assess where things are at the end of this weekend and how to best move over.  This should keep things simple/less I don't have admin for XYZ issues etc.

**Comment by rockfordlhotka** [comment]
I have a sub we can use for the weekend, no problem. After the weekend we'll need to move it over, but if everything is script-based that should be fairly straightforward?

**Comment by tonysurma** [comment]
sure, we can talk on how to proceed after the weekend.  Even if it isn't script based it shouldn't be that bad as there should only be a few moving parts in Azure for this

**Comment by rockfordlhotka** [comment]
I created a resource group and gave @jwendl admin permissions to it.

**Comment by rockfordlhotka** [comment]
http://mobilekidsidapp.azurewebsites.net/
