### ISSUE TITLE
In windows, tab key does not advance to next field

### ISSUE THREAD

**Issue by TeresaLhotka** [HTBox/MobileKidsIdApp#241]
This occurred on the "basic details" page when entering a new child. have not yet tested in other pages

**Comment by devfables** [comment]
I reviewed this briefly while looking into other controls and I am not seeing a good way yet to do this with the current controls being used for data entry fields in Xamarin.Forms. TableView>TableSection>EntryCell

**Comment by rockfordlhotka** [comment]
No help here 😢 
https://forums.xamarin.com/discussion/59429/how-to-set-the-tab-order-on-windows-to-support-keyboard-usage

**Comment by rockfordlhotka** [comment]
Closing because we're dropping support for Windows.
