### ISSUE TITLE
Instruction Screen - About International Parental Abduction

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#25]
**STORY:** As a Kids ID App user, I want to find information about international parental abduction, so I can be informed and take the necessary prevention steps.

**ASSUMPTIONS**
User is logged in, and has navigated to the About International Parental Abduction instruction screen.

**ACCEPTANCE CRITERIA**
The About International Parental Abduction instruction screen will contain the text included in the referenced attachment, including section headers.

**REFERENCES**
[About International Parental Abduction copy v2.docx](https://github.com/HTBox/MobileKidsIdApp/files/138216/About.International.Parental.Abduction.copy.v2.docx)

**Comment by tlhotkamcm** [comment]
If you believe that your child may have been taken out of the country by their abductor, you will want to have these resources at the ready:

Should read "If you believe your child may be taken..."

**Comment by alexlarsongit** [comment]
@tlhotkamcm Thanks for catching that.  I've updated v2 of the copy with your correction.

**Comment by tlhotkamcm** [comment]
Thank you. Im pretty sure it was the result of my many fast edits of my copy in a short time.

-----Original Message-----

**Comment by usernamesarepasse** [comment]
#74
