### ISSUE TITLE
Create the MCM about screen content

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#252]
The app now has an MCM about screen, but we need the content for that screen.

**Comment by bseebacher** [comment]
We currently have this version in the app, most of which came from the original codeathon (#19). If @TeresaLhotka is feeling adventurous, we can take the edits directly in this file from the Github browser app. She may need to fork this first (@rockfordlhotka is standing by).

https://github.com/HTBox/MobileKidsIdApp/blob/master/src/MobileKidsIdApp/MobileKidsIdApp/Resources/aboutmcm.html

If not, whatever's easiest is fine with us.
