### ISSUE TITLE
ApplicationDataProvider still implements IsolatedStorage

### ISSUE THREAD

**Issue by snickler** [HTBox/MobileKidsIdApp#255]
The `ApplicationDataProvider` class needs to be updated to use the `System.IO.File` class for data access, as `IsolatedStorage` doesn't work properly with netstandard2.0. 

#240 is an example of what this change entails.

**Comment by snickler** [comment]
I didn't make a folder, I kept it in the root of the application's data folder. I didn't believe any user would need to access the raw text files from outside of the application.

**Comment by snickler** [comment]
We CAN put the app data file in the same location, though.

**Comment by rockfordlhotka** [comment]
We should probably put these in a folder, given that all the devices now have file managers so user's can see what's on their file system.

**Comment by snickler** [comment]
Will do. I'm reading the documentation for using File.IO for Xamarin and they recommend pointing to the Documents folder, anyway. I'll do that and put these files in a folder. Any preference on the folder name?

**Comment by snickler** [comment]
Actually, I'm misspoken on the location. `Environment.SpecialFolder.LocalApplicationData` and `Environment.SpecialFolder.MyDocuments` point to the same location, so all we'll need is just a folder insider of here.

**Comment by rockfordlhotka** [comment]
If we do need a folder name then `MCMKidsIdKit` should work.
