### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by waiholiu** [HTBox/MobileKidsIdApp#259]
Hi just wondering if this project is still active. I'm looking for an open source project to contribute to and this project sounds like it uses the type of technology I want to learn.

However, is there better instructions on how to get started? I tried following the instructions here (https://github.com/HTBox/MobileKidsIdApp/blob/master/docs/Developer%20setup.md) but when I run the Android version, I'm getting 63 errors.

I seem to be able to run the UWP version though.

**Comment by rockfordlhotka** [comment]
Hi @waiholiu, thank you for asking. Yes, this project is active and we've been making some very good progress!

The code in the master branch should build and run on all three platforms. To build the solution you should just need the tools listed in the document you reference (a Mac is _required_ to build the iOS app).

When you say 63 errors, is that at build/compile time, or deploy? Are you deploying to a real device or an emulator?

**Comment by waiholiu** [comment]
I haven't tried building the iOS app cause I'm on a windows machine. 

I can run the UWP version.

I'm running the android version using my phone using the Live Xamarin Player. I'm setting the start up project to MobileKidsIdApp.Android and running from there.

The errors I'm using are similar to below.

> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/External/.nuget/packages/system.threading.threadpool/4.3.0/ref/netstandard1.3/System.Threading.ThreadPool.dll".

I'm also getting some weird dependency warnings. 

> Package 'PInvoke.NCrypt 0.3.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	MobileKidsIdApp.DataAccess	


It could be an Android SDK problem. I'm not too familiar with this but according to the SDK Manager, I have API 27 Oreo 8.1, API 26 Oreo 8.0 and API 25 Nougat 7.1 installed. Which version do I need?

**Comment by rockfordlhotka** [comment]
The ncrypt warnings are a known side effect of using the library. Hopefully the author will update with a netstandard 2 version at some point.

I don’t know about the other error, as this doesn’t fail on the build server or other dev team workstations. I suspect maybe you are right about the Android version. You can look in the Android project to see the target version.
