### ISSUE TITLE
Instruction Screen - About Amber Alerts

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#26]
**STORY:** As a Kids ID App user, I want to find information about Amber Alerts, so I can be informed and take the necessary steps.

**ASSUMPTIONS**
User is logged in, and has navigated to the About Amber Alerts instruction screen.

**ACCEPTANCE CRITERIA**
The About Amber Alerts instruction screen will contain the text included in the referenced attachment, including section headers.

**REFERENCES**
[About Amber Alerts copy.docx](https://github.com/HTBox/MobileKidsIdApp/files/133364/About.Amber.Alerts.copy.docx)

**Comment by usernamesarepasse** [comment]
#74

**Comment by minefortherecord** [comment]
Fixed acronym and a spelling error

[About.Amber.Alerts.copy.pdf](https://github.com/HTBox/MobileKidsIdApp/files/190521/About.Amber.Alerts.copy.pdf)
