### ISSUE TITLE
Instruction Screen - Disaster Preparedness

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#27]
**STORY:** As a Kids ID App user, I want to find information about disaster preparedness, so I can be informed and take the necessary planning steps.

**ASSUMPTIONS**
User is logged in, and has navigated to the Disaster Preparedness instruction screen.

**ACCEPTANCE CRITERIA**
The Disaster Preparedness instruction screen will contain the text included in the referenced attachment, including section headers.

**REFERENCES**
[Disaster Preparedness copy.docx](https://github.com/HTBox/MobileKidsIdApp/files/133418/Disaster.Preparedness.copy.docx)

**Comment by usernamesarepasse** [comment]
#74
