### ISSUE TITLE
Photos Functionality

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#29]
**STORY:** As a Kids ID App user, I want to capture photos of my child in the app, so I can share their photo with others in the event my child goes missing.

**ASSUMPTIONS**
User is logged in, and has at least one Child Profile created.
User has camera and image gallery capabilities on their mobile device.

**ACCEPTANCE CRITERIA**
1. The user can access the Photos capability from the following areas of the Kids ID app:  the Child Basics screen ( #6 ), the Distinguishing Features screen ( #9 ), and the Documents screen ( #30 )
2. The user can use choose to add a photo and be presented with two options:  take a new photo, or select from the mobile device's image gallery.
3. If the new photo option is selected, the mobile device's standard camera functionality will be launched.
4. If the existing photo option is selected, the mobile device's onboard image gallery is launched for the user to select a photo.
5. Once the user takes a new photo or selects an existing photo, they can confirm their selection.
6. The app will return the user to the screen from which they navigated (Child Basics, Distinguishing Features, or Documents screen, respectively).
7. The user will have the option of identifying a primary photo, which will be used for the Child Profile thumbnail image on the Profiles screen ( #4 ).

**Comment by CoderNate** [comment]
I've been doing a little work on this and I'm hoping to have a commit ready soon.

**Comment by rockfordlhotka** [comment]
Excellent!
