### ISSUE TITLE
Child List doesn't populate on iPhone X

### ISSUE THREAD

**Issue by brunck** [HTBox/MobileKidsIdApp#292]
Discovered via the simulator on iPhone X 11.2, and confirmed to work on the simulator iPhone 7 Plus 11.2. Also confirmed to work on physical 7 Plus device 11.3 with recent deploy from App Center, so iPhone X seems to be the problem.

After installing the app on iPhone X on the simulator:

- Enter a child via Child List and the + button. At least first and last names.
- Navigate back a couple of screens to make sure it saves
- Navigate back to Child List. Should see the child you added in the list.
- Quit the app, and restart. Note that you will not see anything in the Child List.

If you debug, you'll see that saved data is loaded from the phone, but during `MobileKidsIdApp.Models.Child_Fetch()` while stepping through it stops stepping after a few lines and displays the Child List before finishing the fetch method.

**Comment by rockfordlhotka** [comment]
Covered by #300
