### ISSUE TITLE
iPhone 6s+ - Cannot add a contact to child 

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#296]
1) Tap "My kids".
2) Tap the + icon on the top right of the screen.
3) In the Name section, click Given, Middle, or Family.  Also click the CONTACT area.

Expected Results:
The user is allowed to enter values in these areas.

Actual Results:
The area is briefly highlighted but cannot be edited.

Tested on iPhone 6s+ Version 11.2.2 (15C202)

**Comment by rockfordlhotka** [comment]
Probably related to #298

**Comment by rockfordlhotka** [comment]
Covered by #288
