### ISSUE TITLE
Android - Contact info cannot be filled out

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#298]
In Android, in Basic Details, if the user clicks on the Contact section, nothing happens.

Steps to Reproduce:
1) Tap My Kids.
2) Tap on an existing child in the Child List or create a new entry.
3) Tap on the Contact field (blank space below the word Contact).

Expected Result:
The user is able to enter contact info.

Actual Result:
The field briefly flashes but no info can be entered.

Tested on Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment]
Duplicate of #288
