### ISSUE TITLE
Distinguishing Features - Photo cannot be uploaded

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#299]
In the Distinguishing Features section, nothing happens when tapping the SELECT PHOTO button.

Steps to Reproduce:
1) Select My Kids.
2) Select an existing entry from the Child List.
3) Tap DISTINGUISHING FEATURES.
4) Tap the + icon.
5) Tap the SELECT PHOTO button.

Expected Result:
The user is able to upload a photo to the app.

Actual Result:
The button flashes briefly, but no photo can be added.

Tested on Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment]
Should be addressed by #227
