### ISSUE TITLE
Family - + button is not functional

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#301]
In the Family section, if the user taps the + button, nothing happens.

Steps to Reproduce:

1) Select My Kids.
2) Select an existing entry from the Child List.
3) Tap FAMILY.
4) Tap the + icon.

Expected Result:
The user is able to add Family info.

Actual Result:
The button flashes briefly, but no info can be added.

Tested on Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment]
Duplicate of #16
