### ISSUE TITLE
Care Providers - Clinic name, Address, and Phone are filled out simultaneously

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#303]
In Care Providers, if the user edits either the Clinic name, Address, or Phone fields, all three fields will be filled out simultaneously with the same info.

Steps to Reproduce:
1) Select My Kids.
2) Select an existing entry from the Child List.
3) Tap Care Providers.
4) Tap Clinic name, Address, or Phone.
5) Begin typing.

Expected Result:
Only the information in the selected section is filled out.

Actual Result:
Information on all three of the sections is filled out simultaneously with the same values.

Tested on Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment]
Also, with the latest code as of today (Nov 12) when you do this and back out of the page the app crashes (on Android).
