### ISSUE TITLE
Photos - The + button is not functional

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#304]
In the Photos section, if the user taps the + button, nothing happens.

Steps to Reproduce:

1) Select My Kids.
2) Select an existing entry from the Child List.
3) Tap PHOTOS.
4) Tap the + icon.

Expected Result:
The user is able to add a photo.

Actual Result:
The button flashes briefly, but no photo can be added.

Tested on Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment]
Should be addressed by #227
