### ISSUE TITLE
Rework landing screen to be child-centric

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#312]
The current landing screen (4 boxes) is really a placeholder.

A better user experience would be for the user to land directly on the list of children, with the other advanced/extra features available from a hamburger menu.

**Comment by bseebacher** [comment]
Current thinking (Summer 2019) is to rework the UI to use the new Xamarin Forms 4 Shell. 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/introduction

This new framework does not include built-in support for login workflows. See this issue for a possible workaround.

https://github.com/xamarin/Xamarin.Forms/issues/5272

**Comment by rockfordlhotka** [comment]
Closing this, as it will be handled via the Shell implementation in #342
