### ISSUE TITLE
Settings - Logout

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#33]
**STORY:**  As a Kids ID app user, I want to log out of the app, so that I can keep my child's information secure.

**ASSUMPTIONS**
User is logged in.
User has navigated to the Settings screen ( #32 )

**ACCEPTANCE CRITERIA**
1) The user can choose the "Log Out" option from the Settings menu, and be logged out of the app.
2) The user is returned to the splash/Log In screen ( #3 )

**REFERENCES**
[Kids ID App screen flow v5.pdf](https://github.com/HTBox/MobileKidsIdApp/files/139742/Kids.ID.App.screen.flow.v5.pdf)

**Comment by alexlarsongit** [comment]
Updated the flow doc to v3

**Comment by alexlarsongit** [comment]
Updated the flow diagram to v4, adding share button on Profiles screen, disclaimer screens.

**Comment by alexlarsongit** [comment]
Updated flow diagram to v5:
- Merged the doctor and dentist screens into a Professional Care Providers screen.

**Comment by rockfordlhotka** [comment]
Should be implemented as part of #158
