### ISSUE TITLE
Remove Windows UWP project from solution

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#339]

**Comment by snickler** [comment]
Removing Desktop support?

**Comment by rockfordlhotka** [comment]
Yes, we've decided it isn't worth it, especially given that the new `Shell` feature in Xamarin only supports iOS and Android.

The vast majority of people use their phones as a primary computing tool, only sometimes falling back to a desktop/laptop/tablet.

**Comment by snickler** [comment]
This makes sense to me. Maybe in the future, desktop support can be revisited again with the possibility of Windows/Mac targets existing as read-only data points from the phones?

**Comment by bseebacher** [comment]
A moment of silence is in order...
