### ISSUE TITLE
Create database schema for child profile data

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#34]
Required for #6, #7, #8, #9, #10, #12

**Comment by alexlarsongit** [comment]
Adding preliminary data list for the Kids ID App database.
[Kids ID App Data.xlsx](https://github.com/HTBox/MobileKidsIdApp/files/138988/Kids.ID.App.Data.xlsx)

**Comment by bseebacher** [comment]
Our current working approach is to store the data as a serialized JSON document. Since we're not storing very much data and don't have much in the way of reporting needs, loading the whole object graph into memory and storing it out this way should do just fine.

We should be able to do this using a combination of the Cordova File plugin (access to local storage) and an encryption plugin. 

https://github.com/apache/cordova-plugin-file

From reading this, target directory should be cordova.file.dataDirectory .

**Comment by lonerhino** [comment]
gender and gender identity are missing from the data structure for the Children.
General notes filed was added to the structure - for use on any person-related data. @alexlarsongit

**Comment by alexlarsongit** [comment]
@lonerhino After discussion with Teresa, added fields for Sex, Gender Identity and General Notes to v2 of the Data list. 
[Kids ID App Data v2.xlsx](https://github.com/HTBox/MobileKidsIdApp/files/139352/Kids.ID.App.Data.v2.xlsx)

**Comment by alexlarsongit** [comment]
@lonerhino @bseebacher  New requirement ( #62 ) for acknowledging a splash screen with legal/security notice about data security.  We will need to save the state of that acknowledgement in the data set.  See updated data list below.
[Kids ID App Data v3.xlsx](https://github.com/HTBox/MobileKidsIdApp/files/139372/Kids.ID.App.Data.v3.xlsx)

**Comment by alexlarsongit** [comment]
@lonerhino @bseebacher New requirement ( #70 ) for segmenting profile/app data by login/JWT token.  We will need to store a key to associate child profiles, settings by login.  See updated data list below.
[Kids ID App Data v4.xlsx](https://github.com/HTBox/MobileKidsIdApp/files/139415/Kids.ID.App.Data.v4.xlsx)

**Comment by bseebacher** [comment]
Did a little more reading on the subject of local storage options last night. According to this, on top of having hard limits of 5 MB, the local file storage option may not be as reliable as we need it to be.

http://www.joshmorony.com/a-summary-of-local-storage-options-for-phonegap-applications/

I'm still thinking a NoSQL document database approach would make the most sense from a development perspective, but the back end might be best served by something like this, which would handle the details of object serialization and persistence for us. It also includes support for Ionic and Angular, which may take care of getting data to the view layer for us.

https://github.com/mozilla/localForage
https://github.com/thgreasi/localForage-cordovaSQLiteDriver

I'm going to tinker with this today.

**Comment by alexlarsongit** [comment]
Assumption from discussion with @bseebacher  -- the database will not store the full list of selection field options, just the user's selection.

**Comment by alexlarsongit** [comment]
Updated Data List v5:  [Kids ID App Data v5.xlsx](https://github.com/HTBox/MobileKidsIdApp/files/139849/Kids.ID.App.Data.v5.xlsx)

This depicts the merging of the doctor/dentist info into single Professional Care Provider entity.
