### ISSUE TITLE
Change landing/navigation to use new Shell feature in Xamarin

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#342]
Related to #312

**Comment by jacob-maristany** [comment]
While Shell navigation for XF can ramp up initial development of an app, it has many limitations and outstanding issues. Any shell navigation has been removed in [PR 360](https://github.com/HTBox/MobileKidsIdApp/pull/360). The drawer UI has been replaced, which is more intuitive and has a better workflow for the content.
