### ISSUE TITLE
Friends page no manual input

### ISSUE THREAD

**Issue by thenewmona** [HTBox/MobileKidsIdApp#351]

**Comment by thenewmona** [comment]
As a grandparent, I do not have my grandchildren's in my contact list. 

I would like the ability to add the kid's information manually

**Comment by rockfordlhotka** [comment]
I was just talking to @TeresaLhotka about this the other day, whether it was best to follow our thought process that people can leverage the existing contact management feature built into the phone, or if we needed to implement our own duplicate contact management behavior.

@thenewmona, are you reluctant to add your grandchild to your phone's contact list? If so, can you help us understand why?

**Comment by thenewmona** [comment]
@rockfordlhotka I have no issue adding my grandaughter , she actually is a contact on my phone.
I guess maybe I am misunderstanding what the friends page is for. 
I thought it is for my granddaughter's friends. 
 I do not have her friends as contacts on my phone, but for this app, I would like the ability to put them in manually. 
Does that make sense

**Comment by rockfordlhotka** [comment]
Yes, I think the word "friends" was missing in the original description.

That's what @TeresaLhotka and I were talking about, though from the perspective of being parents, so perhaps it isn't the same with grandparents.

I, for example, didn't have my kids' friends in my phone, but my wife did. So the train of thought we followed was why _wouldn't_ you put them in your phone? That way you can call/text/email them because they are part of the contacts system of the phone, vs if we create our own contact system inside the app none of those features would exist.

**Comment by jacob-maristany** [comment]
After discussing with @rockfordlhotka , we are removing the ability to select contacts from the device and replacing with manual entry entirely based on the following: 

a) the limited information contact picking provides and what is used
b) the potential for irrelevant and informal information (e.g. "Grandpa Jacob", "Joe", "My son's friend") and how limited the functionality is based on the contacts on the user's specific device
c) how unintuitive the value or functionality of the feature is to the user
d) as an app that cares significantly about PII, restricting app permissions that aren't really needed for critical features

**Comment by TeresaLhotka** [comment]
Good Morning JAcob!

Thank you so much for all of your work on this project, and for the update. These modifications make sense to me.
I also feel that needing to manually enter the information could spark more interaction between parent and child regarding the child’s friends - and important factor in child safety.

Thank you again for all that you do!
Teresa



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
