### ISSUE TITLE
Set up Hockeyapp to support testing

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#37]

**Comment by Bowman74** [comment]
There are two apps for this in HockeyApp. This is under the account for your personal email Rocky. You will have to invite people to use it but you will have full control.

For the Android app, make sure you sign any APKs or the testers will have to keep uninstalling the app every time they upgrade.

You will 100% have to sign the iOS versions. That's complicated and I will have to get you provisioning profiles installed on the Mac. When you are ready let me know as you will need my help.

**Comment by Chuxel** [comment]
I can help here as well. We'll likely want to persist encrypted versions of the P12 of the signing cert and mobile provisioning profiles in the repo and then decrypt and install during CI for the build.  There's a trick to automating that that was implemented in the [VSTS extension for Cordova](https://github.com/Microsoft/vsts-cordova-tasks).  We can adapt the approach for Appveryor.  Otherwise we could have devs inadvertently invalidating the CI dev cert for example.

**Comment by Chuxel** [comment]
Okay in between helping folks I generated some test dev and ad hoc signing certs and a provisioning profile under Rocky's account.  These have then been encrypted and placed in the source repo.  Ditto with a release.keystore for the Android build. 

I then modified the gulp file with to pass in the appropriate args and accept environment args for the decryption and keystore passwords.

ENC_PWD
P12_PWD
ANDROID_PWD

I'll PM Rocky with the info. 

For Windows it expects openssl.exe to be available for decryption - which is normally available if the git command line tools are installed.

I need to clean up things and finish up iOS but you can see what I've done so far here: https://github.com/Chuxel/MobileKidsIdApp

**Comment by Chuxel** [comment]
Added https://github.com/HTBox/MobileKidsIdApp/pull/75 which also includes some additional detail on what is going on.

There's an encrypted ad-hoc profile and associated p12 file in the repo now.  When you set the above env vars doing a gulp build-android-release and gulp build-ios-release will decrypt and use them. 

You can encrypt a file on a Mac just using "openssl des3 -in <filename> -out <filename>" and entering a password.

**Comment by Chuxel** [comment]
FYI - I have the start of an automated hockey app deployment task.  It works for iOS already, need to validate android.

You'll be able to automate upload like this:

gulp build-ios-release hockeyapp-ios-release

https://github.com/Chuxel/MobileKidsIdApp

**Comment by rockfordlhotka** [comment]
Is that something we'd want in our normal CI build?

**Comment by Chuxel** [comment]
Depending on your process, yes.  You can set things up to automatically build, sign, and upload the apk to hockeyapp.  Anyone then going to hockeyapp to download then would get the latest successful build. 

In bigger projects I setup a "beta" branch that I then a separate build to trigger the hockeyapp task.  A simple merge into the beta branch then publishes to Hockey.

About to submit a PR for this.

**Comment by rockfordlhotka** [comment]
I think the beta branch solution makes a lot more sense - we don't need/want to redeploy for every little PR that comes into master.

**Comment by Chuxel** [comment]
Yep - In VSTS we have release management drive the hockeyapp deploy (which allows manual gates, etc), but when there's no RM capability the beta branch is the way to go.

Here's the PR.

https://github.com/HTBox/MobileKidsIdApp/pull/87

It assumes you've setup the iOS / Android signing environment vars.
