### ISSUE TITLE
Create Child Profiles

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#4]
**STORY:**  As a Kids ID App user, I want to create a profile for my child, so I can gather vital information about my child in the case my child goes missing.

**ASSUMPTIONS:**
The user can create an unlimited number of child profiles.

**ACCEPTANCE CRITERIA:**
1. The user can create one or more profiles for their children.
2. Minimum information needed to create the profile is: First Name, Middle Name, Last Name and DOB. See pg. 7 of attached wireframe.
3. Once minimum info entered, user can save the child profile.
4. Child profile is displayed as photo and first name, age in years, and checklist completion percentage. See pg. 5 of attached wireframe.
5. If no photo is selected, a generic profile icon is displayed in the child profile entry.
6. If photo is selected, the photo is displayed as a thumbnail image in the child profile entry.
7. Once the profile is saved, the user is directed to a Profiles screen.
8. If multiple profiles are created, the Profiles screen will display cards for each profile, per item 4 above.
9. Tapping child profile image/entry sends user to the Child Info menu screen.  

[MCM.pdf](https://github.com/HTBox/MobileKidsIdApp/files/120988/MCM.p)

**Comment by alexlarsongit** [comment]
Child Profiles should be segmented by login/JWT token #70

**Comment by rockfordlhotka** [comment]
A lot of work related to this task has been done under #6 and #5, so I'm closing this issue - remaining work will be tracked by those two issues.
