### ISSUE TITLE
Create Child Info > Child Basics Screen

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#6]
**STORY:**  As a Kids ID App user, I want to enter general information about my child, so I can have it available should my child go missing.

**ASSUMPTIONS**
User is logged in, and has created at least one child profile.
User has navigated from the Child Info menu screen to "Child Basics" option.

**ACCEPTANCE CRITERIA**
1) The Child Basics screen displays the following info:  thumbnail image(optional), First Name, Middle Name, Last Name and DOB.  See page 7 of attached wireframes.
2) If a photo has been added, the thumbnail will display the primary photo as a thumbnail.
3) If a photo has not been added, the thumbnail will display a generic user icon.
4) First Name field is a required text field of 50 characters
5) Middle Name field is a required text field of 50 characters
6) Last Name field is a required text field of 50 characters
7) Date of Birth (DOB) is a required date field (DD/MM/YYYY), with option to enter date, or select from a calendar date picker.
**ADDITIONAL CRITERIA ADDED 3/26**
8) App will store: First Name, Middle Name, Last Name, Date of Birth -- the minimum fields required to create the profile and the minimum information needed to submit a police report for a missing child.
9) Add a button to the screen for "Link Contact" to optionally link the child's app profile to a phone contact.
-- If the user clicks the Link Contact button, the user is sent to their onboard phone Contacts to search for a contact.
-- Once a contact is selected, the additional information stored in that Contact is loaded onto the profile screen.
10) Other information, such as addresses, phone numbers, email addresses will be stored in the phone Contact.
11) If the user links a Contact prior to filling in First Name, Middle Name, Last Name and DOB, the app will fill the fields with any applicable data it finds in the contact. Any info name or DOB info missing from the contact will remain unfilled. 
12) The child profile cannot be saved until the required fields (First Name, Middle Name, Last Name and DOB) are entered, or populated from a linked Contact.

**REFERENCES**
[MCM.pdf](https://github.com/HTBox/MobileKidsIdApp/files/120988/MCM.p)

**Comment by alexlarsongit** [comment]
Assumption from #34 - UI will store the selection options for drop-down menus.  DB will only store the user's selection.

**Comment by alexlarsongit** [comment]
Discussion regarding whether we should use mobile phone's Contact for the child itself:  
-- We want to avoid redundant storing of information, if we can help it. So child could be made a Contact on the phone?
-- But we also want to prevent accidental deletion of the child Contact from the phone.

**Decision**
1) App will store: FirstName, MiddleName, LastName, Date of Birth -- the minimum needed to create the profile and the minimum needed to submit a police report for a missing child.
2) Add a button to the screen for "Link Contact" to optionally link the child's app profile to a phone contact.
-- If the user clicks the Link Contact button, the user is sent to their onboard phone Contacts to search for a contact.
-- Once a contact is selected, the additional information stored in that Contact is loaded onto the profile screen.
3) Other information, such as addresses, phone numbers, email addresses will be stored in the phone Contact.
4) If the a

**Comment by rockfordlhotka** [comment]
This issue has been implemented in Xamarin, but the button to link a device contact to the child remains to be done.
