### ISSUE TITLE
Create Child Info > Measurements Screen 

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#7]
**STORY:** As a Kids ID App user, I want to enter my child's height and weight measurements, so I can have current information on hand in case my child goes missing.

**ASSUMPTIONS**
User is logged in, and has created at least one child profile.
User has navigated from the Child Info menu screen to "Measurements" option.

**ACCEPTANCE CRITERIA**
1) The Measurements screen displays the following info for each entry: height, weight, and date field.
2) The user can enter and save multiple entries of measurement records.
3) The Height field is alphanumeric text, allowing entry of numbers, letters, or special characters like ' and ".  (Examples:  3'2", 3 ft 2 in, 96.5 cm)
4) The Weight field is alphanumeric text, allowing entry of numbers and letters. (Examples: 42.5 lbs, 20 lbs 4 oz, 19 kg)
5) The date field will be in DD/MM/YYYY format, defaulted to today's date, with date entry or selection from date picker. 

**REFERENCES**
[MCM.pdf](https://github.com/HTBox/MobileKidsIdApp/files/120988/MCM.p)

**Comment by rockfordlhotka** [comment]
I'm going to work on this screen.

**Comment by alexlarsongit** [comment]
Upon discussion, we will combine this screen with the #8 Physical Details Screen.  This no longer needs to be its own screen, and the Height/Weight fields will move to the Physical Details Screen.

**Comment by alexlarsongit** [comment]
Closing issue.
