### ISSUE TITLE
Segment app data by login/JWT token

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#70]
**STORY:**  As a Kids ID App user, I want to secure the data I store in the app by my login, so I can restrict access to my child's information.

**ASSUMPTIONS**
User has created at least one child profile.

**ACCEPTANCE CRITERIA**
1) An authenticated user can only view child profile / app data created with their login.
2) All data in the data model needs to be associated with the login/account. (new data element?)
3) A secondary user who launches the application cannot access the 

**REFERENCES**
Login Issue: #3 
Data List: https://github.com/HTBox/MobileKidsIdApp/files/139415/Kids.ID.App.Data.v4.xlsx

**Comment by rockfordlhotka** [comment]
Being addressed in #89
