### ISSUE TITLE
Create Local Storage Data Persistence Layer

### ISSUE THREAD

**Issue by bseebacher** [HTBox/MobileKidsIdApp#79]
Requirements 

- Create, Load, Delete system entities 
- Handle interactions with local storage subsystems
- Provide interface to UI for interaction with data entities

Candidate Approach

https://github.com/mozilla/localForage
https://github.com/thgreasi/localForage-cordovaSQLiteDriver

**Comment by rockfordlhotka** [comment]
Encryption will be handled by #89, so this item is now considered closed, as we have a working persistence layer.
