### ISSUE TITLE
Create Child Info > Physical Details Screen

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#8]
**STORY:** As a Kids ID App user, I want to keep track of my child's physical description, in case I need to share the information if my child goes missing.

**ASSUMPTIONS**
User is logged in, and has created at least one child profile.
User has navigated from the Child Info menu screen to "Physical Details" option.

**ACCEPTANCE CRITERIA**
1) The Physical Details screen has fields to enter the following information: **height**, **weight**, hair color, hairstyle, eye color, glasses, contacts, skin tone, racial/ethnic identity, sex and gender identity.
2) The Hair Color, Eye Color, and Skin Tone fields will be drop-down selection fields (select one).  
3) The Racial/Ethnic Identity field will be a multi-select checkbox list (check all that apply).
4) The Hair Color field will have the following options:
5) The Eye Color field will have the following options: Dark/light brown, Dark/light green, Dark/light blue, Hazel, Black.
6) The Skin Tone field will have the following options: Light, Fair, Medium, Olive, Brown, Dark.
7) The Racial/Ethnic Identity field will have the following options, defaulted to UNchecked: African American, Asian, Caucasian, Hispanic (non-white), Native American, Pacific Islander.
8) Hairstyle field will be text of 255 characters to describe hairstyle.
9) Sex and Gender Identity fields will be text of 255 characters to allow user to enter most appropriate terms.
**ADDITIONAL ACCEPTANCE CRITERIA 3/26**
10) The Height field is alphanumeric text, allowing entry of numbers, letters, or special characters like ' and ". (Examples: 3'2", 3 ft 2 in, 96.5 cm)
11) The Weight field is alphanumeric text, allowing entry of numbers and letters. (Examples: 42.5 lbs, 20 lbs 4 oz, 19 kg)

**REFERENCES**
[MCM.pdf](https://github.com/HTBox/MobileKidsIdApp/files/120988/MCM.p)

**Comment by alexlarsongit** [comment]
Added field for hairstyle description.

**Comment by alexlarsongit** [comment]
Added fields for Sex and Gender Identity.
Assumption from #34 - UI will store the selection options for drop-down menus.  DB will only store the user's selection.

**Comment by alexlarsongit** [comment]
Combining this screen with #7 Measurements Screen functionality. The Height/Weight fields from Measurements will be added to this screen.

**Comment by rockfordlhotka** [comment]
```
interface PhysicalDetails{
    id : string
    height?: string
    weight?: string
    measurementDate?: Date
    hairColor?: string 
    hairStyle?: string 
    eyeColor?: string 
    eyeGlasses?: boolean
    eyeContacts?: boolean
    skinTone?: string
    racialEthnicIdentity?: string 
    gender?: string
    genderIdentity?: string
}
```
