### ISSUE TITLE
Create Child Info > Distinguishing Features Screen

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#9]
**STORY:**  As a Kids ID App user, I want to record my child's distinguishing features, in case I need to share the information should my child go missing.

**ASSUMPTIONS**
User is logged in, and has created at least one child profile.
User has navigated from the Child Info menu screen to "Distinguishing Features" option.

**ACCEPTANCE CRITERIA**
1) The Distinguishing Features screen will have the ability to enter one or more entries for distinguishing features.
2) Entries for distinguishing features will include text description field, and ability to add a photo related to that entry.
3) Photos can be selected from the mobile device's image gallery.
4) Entries can also be associated with a location on a child body diagram. See reference link below for an example of a diagram.

**REFERENCES**
Wireframes: [MCM.pdf](https://github.com/HTBox/MobileKidsIdApp/files/120988/MCM.p)

These diagrams are free to use:
Example of front/back body diagram: 
http://www.fflm.ac.uk/wp-content/uploads/documentstore/1370339496.JPG

Example of right/left body diagram:
http://www.fflm.ac.uk/wp-content/uploads/documentstore/1370339395.JPG

**Comment by alexlarsongit** [comment]
Updated links for body diagrams.

**Comment by rockfordlhotka** [comment]
I have this page basically implemented other than the button to select a photo.

However, I'm not real pleased with the visual feel of the implementation, and I suspect there's a better way to implement the visual layout.

**Comment by rockfordlhotka** [comment]
The MobileKidsIdApp.Controls.RepeaterView control seems like a very good way to create scrolling edit views for small numbers of items (like the distinguishing features or care providers).

The only remaining feature in this work item now is a photo picker to select photos of the distinguishing feature.
