### ISSUE TITLE
Linking Additional Social Media Logins

### ISSUE THREAD

**Issue by alexlarsongit** [HTBox/MobileKidsIdApp#94]
**STORY:** As a Kids ID App user, I want to link my additional social media accounts to my app, so I can use other social media authentications to access the app.

**ASSUMPTIONS**
User is already logged in.
User has additional social media accounts to link.

**ACCEPTANCE CRITERIA**
1) Once user is logged in, they are able to link additional social media accounts to their app. 
2) Social media accounts supported are Facebook, Twitter, Google and Hotmail.

**REFERENCES**
None

**Comment by alexlarsongit** [comment]
Unsure whether linking social media accounts option should be accessible through the Settings screen, or from a successful authentication screen or the home landing page?  Suggestions welcome!

**Comment by rockfordlhotka** [comment]
We are no longer using social media for login.
